export const ARTIST_ALIAS = {
    "Akdong Musician": "AKMU",
    "Blackpink": "BLACKPINK",
    "C418": "Various",
    "Hans Zimmer": "Various",
    "Harold Faltermeyer": "Various",
    "Ive": "IVE",
    "James Horner": "Various",
    "Kessoku Band": "結束バンド",
    "Kim Kwang Seok": "김광석",
    "Kristen Anderson-Lopez": "Various",
    "League of Legends": "Various",
    "Lee Chanhyuk": "이찬혁",
    "Mariya Takeuchi": "竹内まりや",
    "Miki Matsubara": "松原みき",
    "Shiro Sagisu": "Various",
    "Tatsuro Yamashita": "山下達郎",
    "Yoasobi": "YOASOBI",
};