export const ARTIST_ALIAS = {
    "Aimyon": "あいみょん",
    "Akdong Musician": "AKMU",
    "Blackpink": "BLACKPINK",
    "C418": "Various",
    "Hans Zimmer": "Various",
    "Harold Faltermeyer": "Various",
    "Ive": "IVE",
    "James Horner": "Various",
    "Kessoku Band": "結束バンド",
    "Kim Kwang Seok": "김광석",
    "Kristen Anderson-Lopez": "Various",
    "Labrinth": "LSD",
    "League of Legends": "Various",
    "Lee Chanhyuk": "이찬혁",
    "Mariya Takeuchi": "竹内まりや",
    "Miki Matsubara": "松原みき",
    "Radwimps": "RADWIMPS",
    "Seiko Matsuda": "松田聖子",
    "Shiro Sagisu": "Various",
    "Tatsuro Yamashita": "山下達郎",
    "Yoasobi": "YOASOBI",
};

export const ARTIST_COUNTRY = {
    "5 Seconds Of Summer": "US & Europe 🇺🇸🇪🇺",
    "aespa": "South Korea 🇰🇷",
    "Aimyon": "Japan 🇯🇵",
    "Aiobahn": "Japan 🇯🇵",
    "Akdong Musician": "South Korea 🇰🇷",
    "Ariana Grande": "US & Europe 🇺🇸🇪🇺",
    "BLACKPINK": "South Korea 🇰🇷",
    "BTS": "South Korea 🇰🇷",
    "Beenzino": "South Korea 🇰🇷",
    "Billie Eilish": "US & Europe 🇺🇸🇪🇺",
    "Blackpink": "South Korea 🇰🇷",
    "Bruno Mars": "US & Europe 🇺🇸🇪🇺",
    "C Jamm": "South Korea 🇰🇷",
    "Camila Cabello": "US & Europe 🇺🇸🇪🇺",
    "Charlie Puth": "US & Europe 🇺🇸🇪🇺",
    "Chet Baker": "US & Europe 🇺🇸🇪🇺",
    "Cigarettes After Sex": "US & Europe 🇺🇸🇪🇺",
    "Coldplay": "US & Europe 🇺🇸🇪🇺",
    "Cyndi Lauper": "US & Europe 🇺🇸🇪🇺",
    "Daft Punk": "US & Europe 🇺🇸🇪🇺",
    "Doja Cat": "US & Europe 🇺🇸🇪🇺",
    "Gallant": "US & Europe 🇺🇸🇪🇺",
    "Harry Styles": "US & Europe 🇺🇸🇪🇺",
    "IU": "South Korea 🇰🇷",
    "Imagine Dragons": "US & Europe 🇺🇸🇪🇺",
    "Ive": "South Korea 🇰🇷",
    "Jisoo": "South Korea 🇰🇷",
    "Justin Bieber": "US & Europe 🇺🇸🇪🇺",
    "Kessoku Band": "Japan 🇯🇵",
    "Kim Kwang Seok": "South Korea 🇰🇷",
    "Labrinth": "US & Europe 🇺🇸🇪🇺",
    "Lauv": "US & Europe 🇺🇸🇪🇺",
    "Lee Chanhyuk": "South Korea 🇰🇷",
    "Lisa": "South Korea 🇰🇷",
    "Mariah Carey": "US & Europe 🇺🇸🇪🇺",
    "Mariya Takeuchi": "Japan 🇯🇵",
    "Maroon 5": "US & Europe 🇺🇸🇪🇺",
    "Miki Matsubara": "Japan 🇯🇵",
    "Nirvana": "US & Europe 🇺🇸🇪🇺",
    "Norah Jones": "US & Europe 🇺🇸🇪🇺",
    "Olivia Rodrigo": "US & Europe 🇺🇸🇪🇺",
    "Post Malone": "US & Europe 🇺🇸🇪🇺",
    "Queen": "US & Europe 🇺🇸🇪🇺",
    "Radwimps": "Japan 🇯🇵",
    "Rosé": "South Korea 🇰🇷",
    "Sabrina Carpenter": "US & Europe 🇺🇸🇪🇺",
    "Seiko Matsuda": "Japan 🇯🇵",
    "Shiro Sagisu": "Japan 🇯🇵",
    "Silica Gel": "South Korea 🇰🇷",
    "Silk Sonic": "US & Europe 🇺🇸🇪🇺",
    "SZA": "US & Europe 🇺🇸🇪🇺",
    "Tatsuro Yamashita": "Japan 🇯🇵",
    "Taylor Swift": "US & Europe 🇺🇸🇪🇺",
    "The Chainsmokers": "US & Europe 🇺🇸🇪🇺",
    "The Weeknd": "US & Europe 🇺🇸🇪🇺",
    "Yoasobi": "Japan 🇯🇵",
    "검정치마": "South Korea 🇰🇷",
    "조광일": "South Korea 🇰🇷",
    "한로로": "South Korea 🇰🇷",
};

export const ALBUM_COUNTRY = {
    "Frozen The Songs": "US & Europe 🇺🇸🇪🇺",
    "Minecraft Volume Alpha": "US & Europe 🇺🇸🇪🇺",
    "Black Panther The Album (Music From And Inspired By)": "US & Europe 🇺🇸🇪🇺",
    "Spider-Man: Into The Spider-Verse (Music From & Inspired By The Motion Picture)": "US & Europe 🇺🇸🇪🇺",
    "Evangelion Finally": "Japan 🇯🇵",
    "Interstellar (Original Motion Picture Soundtrack)": "US & Europe 🇺🇸🇪🇺",
    "Titanic (Music From The Motion Picture)": "US & Europe 🇺🇸🇪🇺",
    "Top Gun: Maverick - Music From The Motion Picture": "US & Europe 🇺🇸🇪🇺",
    "알고있지만, (Original Sound Track)": "South Korea 🇰🇷",
    "Frozen: The Songs": "US & Europe 🇺🇸🇪🇺",
    "League Of Legends Worlds Anthems - Vol. 1: 2014-2023": "US & Europe 🇺🇸🇪🇺",
}