name: Scrape Discogs

on:
  push:
    branches:
      - main
    paths:
      - "discogs/**"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # Every Monday at 00:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Get dependencies & build
        run: |
          pnpm install
          pnpm build
        working-directory: discogs

      - name: Scrape Discogs
        run: node discogs/dist/index.js > list.json
        env:
          DISCOGS_USERNAME: "kyle-seongwoo-jun"
          DISCOGS_API_KEY: ${{ secrets.DISCOGS_API_KEY }}

      - name: Get current date
        id: date
        run: |
          echo "CURRENT_DATE=$(date +'%b %d, %Y')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "feat: update list.json on ${{ steps.date.outputs.CURRENT_DATE }}"
          commit-message: "feat: update list.json on ${{ steps.date.outputs.CURRENT_DATE }}"
          branch: scrape-discogs
